# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  Deployment:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Build and Test
      run: |
        touch .env
        echo "${{ secrets.PROD_ENV_FILE }}" > .env
        sudo apt-get -y update
        npm install
        npm run build:sahat
        npm run cover
        npm run lint:scripts
    - name: Running pm2
      run: |
        pm2 restart server



